package br.com.test.dynamo.dynamodbtest.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;
import lombok.Data;
import java.util.Date;
import java.util.UUID;

@DynamoDBTable(tableName = "Task")
@Data
public class Task {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID id;
    private String name;
    private String description;
    private Priority priority;
    @DynamoDBTypeConvertedTimestamp
    private Date insertDate = new Date();

}
